apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: 23-239-30-65.ip.linodeusercontent.com/marketplace/proxy
      imagePullSecrets:
      - name: secret-harbor