apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: harbor.tupi.im/marketplace/proxy:0.1.0-1-stable
      imagePullSecrets:
      - name: secret-harbor