apiVersion: v1
kind: Service
metadata:
  name: db-authentication
spec:
  # type: ClusterIP
  # ports:
  # - name: db-authentication
  #   port: 5429
  #   targetPort: 5432
  #   protocol: TCP 
  # selector:
  #   app: db-authentication

  type: NodePort
  ports:
  - name: db-authentication
    port: 5429
    targetPort: 5432
    nodePort: 32002
  selector:
    app: db-authentication
