apiVersion: v1
kind: Service
metadata:
  name: api-datalake-evento
spec:
  type: ClusterIP
  ports:
  - name: api-datalake-evento
    port: 3001
    targetPort: 3001
  selector:
    app: api-datalake-evento
