piVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-datalake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-datalake
  template:
    metadata:
      labels:
        app: db-datalake
    spec:
      containers:
        - name: db-datalake
          image: harbor.tupi.im/marketplace/db-datalake:v0.1.0-1-stable
          ports:
            - containerPort: 5432
              protocol: TCP  

          env:
          - name: POSTGRES_DB
            value: "datalake"
          - name: POSTGRES_PASSWORD
            value: "123456"
          - name: POSTGRES_USER
            value: "postgres"

          volumeMounts:
            - name: db-datalake
              mountPath: /var/lib/postgresql/data

      imagePullSecrets:
      - name: secret-harbor

      volumes:
        - name: db-datalake
          # configMap:
          #   name: db-datalake-configmap


  volumeClaimTemplates:
    - metadata:
        name: db-datalake
      spec:
        accessModes:
          - ReadWriteOnce
        # storageClassName: "manual"
        resources:
          requests:
            storage: 1Gi
